# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Animal.create(animal: "Otter")
Animal.create(animal: "Panda")
Animal.create(animal: "Fox")
Animal.create(animal: "Cat")
Animal.create(animal: "Dog")
Animal.create(animal: "Meerkat")
Animal.create(animal: "Lemur")
Animal.create(animal: "Seal")
Animal.create(animal: "Penguin")
Animal.create(animal: "Bear")
Animal.create(animal: "Wallaby")
Animal.create(animal: "Kangaroo")
Animal.create(animal: "Leopard")
Animal.create(animal: "Lion")
Animal.create(animal: "Jaguar")
Animal.create(animal: "Koala")
Animal.create(animal: "Kiwi")
Animal.create(animal: "Puffin")
Animal.create(animal: "Mouse")
Animal.create(animal: "Rabbit")
Animal.create(animal: "Sheep")
Animal.create(animal: "Squirrel")
Animal.create(animal: "Lynx")
Animal.create(animal: "Ocelot")
Animal.create(animal: "Gnar")
Animal.create(animal: "Owl")
Animal.create(animal: "Porcupine")
Animal.create(animal: "Dolphin")
Animal.create(animal: "Wolf")
Animal.create(animal: "Cheetah")
Animal.create(animal: "Coyote")
Animal.create(animal: "Hippo")
Animal.create(animal: "Swordfish")
Animal.create(animal: "Marmoset")
Animal.create(animal: "Hamster")
Animal.create(animal: "Firefox")
Animal.create(animal: "Beaver")
Animal.create(animal: "Deer")
Animal.create(animal: "Goose")

Adjective.create(kind: "positive", adjective: "Adaptable")
Adjective.create(kind: "positive", adjective: "Adventurous")
Adjective.create(kind: "positive", adjective: "Affable")
Adjective.create(kind: "positive", adjective: "Affectionate")
Adjective.create(kind: "positive", adjective: "Agreeable")
Adjective.create(kind: "positive", adjective: "Ambitious")
Adjective.create(kind: "positive", adjective: "Amiable")
Adjective.create(kind: "positive", adjective: "Amicable")
Adjective.create(kind: "positive", adjective: "Amusing")
Adjective.create(kind: "positive", adjective: "Brave")
Adjective.create(kind: "positive", adjective: "Bright")
Adjective.create(kind: "positive", adjective: "Broadminded")
Adjective.create(kind: "positive", adjective: "Calm")
Adjective.create(kind: "positive", adjective: "Careful")
Adjective.create(kind: "positive", adjective: "Charming")
Adjective.create(kind: "positive", adjective: "Communicative")
Adjective.create(kind: "positive", adjective: "Compassionate ")
Adjective.create(kind: "positive", adjective: "Conscientious")
Adjective.create(kind: "positive", adjective: "Considerate")
Adjective.create(kind: "positive", adjective: "Convivial")
Adjective.create(kind: "positive", adjective: "Courageous")
Adjective.create(kind: "positive", adjective: "Courteous")
Adjective.create(kind: "positive", adjective: "Creative")
Adjective.create(kind: "positive", adjective: "Decisive")
Adjective.create(kind: "positive", adjective: "Determined")
Adjective.create(kind: "positive", adjective: "Diligent")
Adjective.create(kind: "positive", adjective: "Diplomatic")
Adjective.create(kind: "positive", adjective: "Discreet")
Adjective.create(kind: "positive", adjective: "Dynamic")
Adjective.create(kind: "positive", adjective: "Easygoing")
Adjective.create(kind: "positive", adjective: "Emotional")
Adjective.create(kind: "positive", adjective: "Energetic")
Adjective.create(kind: "positive", adjective: "Enthusiastic")
Adjective.create(kind: "positive", adjective: "Exuberant")
Adjective.create(kind: "positive", adjective: "Fairminded")
Adjective.create(kind: "positive", adjective: "Faithful")
Adjective.create(kind: "positive", adjective: "Fearless")
Adjective.create(kind: "positive", adjective: "Forceful")
Adjective.create(kind: "positive", adjective: "Frank")
Adjective.create(kind: "positive", adjective: "Friendly")
Adjective.create(kind: "positive", adjective: "Funny")
Adjective.create(kind: "positive", adjective: "Generous")
Adjective.create(kind: "positive", adjective: "Gentle")
Adjective.create(kind: "positive", adjective: "Good")
Adjective.create(kind: "positive", adjective: "Gregarious")
Adjective.create(kind: "positive", adjective: "Hardworking")
Adjective.create(kind: "positive", adjective: "Helpful")
Adjective.create(kind: "positive", adjective: "Honest")
Adjective.create(kind: "positive", adjective: "Humorous")
Adjective.create(kind: "positive", adjective: "Imaginative")
Adjective.create(kind: "positive", adjective: "Impartial")
Adjective.create(kind: "positive", adjective: "Independent")
Adjective.create(kind: "positive", adjective: "Intellectual")
Adjective.create(kind: "positive", adjective: "Intelligent")
Adjective.create(kind: "positive", adjective: "Intuitive")
Adjective.create(kind: "positive", adjective: "Inventive")
Adjective.create(kind: "positive", adjective: "Kind")
Adjective.create(kind: "positive", adjective: "Loving")
Adjective.create(kind: "positive", adjective: "Loyal")
Adjective.create(kind: "positive", adjective: "Modest")
Adjective.create(kind: "positive", adjective: "Neat")
Adjective.create(kind: "positive", adjective: "Nice")
Adjective.create(kind: "positive", adjective: "Optimistic")
Adjective.create(kind: "positive", adjective: "Passionate")
Adjective.create(kind: "positive", adjective: "Patient")
Adjective.create(kind: "positive", adjective: "Persistent ")
Adjective.create(kind: "positive", adjective: "Pioneering")
Adjective.create(kind: "positive", adjective: "Philosophical")
Adjective.create(kind: "positive", adjective: "Placid")
Adjective.create(kind: "positive", adjective: "Plucky")
Adjective.create(kind: "positive", adjective: "Polite")
Adjective.create(kind: "positive", adjective: "Powerful")
Adjective.create(kind: "positive", adjective: "Practical")
Adjective.create(kind: "positive", adjective: "Proactive")
Adjective.create(kind: "positive", adjective: "Quickwitted")
Adjective.create(kind: "positive", adjective: "Quiet")
Adjective.create(kind: "positive", adjective: "Rational")
Adjective.create(kind: "positive", adjective: "Reliable")
Adjective.create(kind: "positive", adjective: "Reserved")
Adjective.create(kind: "positive", adjective: "Resourceful")
Adjective.create(kind: "positive", adjective: "Romantic")
Adjective.create(kind: "positive", adjective: "Selfconfident")
Adjective.create(kind: "positive", adjective: "Selfdisciplined")
Adjective.create(kind: "positive", adjective: "Sensible")
Adjective.create(kind: "positive", adjective: "Sensitive")
Adjective.create(kind: "positive", adjective: "Shy")
Adjective.create(kind: "positive", adjective: "Sincere")
Adjective.create(kind: "positive", adjective: "Sociable")
Adjective.create(kind: "positive", adjective: "Straightforward")
Adjective.create(kind: "positive", adjective: "Sympathetic")
Adjective.create(kind: "positive", adjective: "Thoughtful")
Adjective.create(kind: "positive", adjective: "Tidy")
Adjective.create(kind: "positive", adjective: "Tough")
Adjective.create(kind: "positive", adjective: "Unassuming")
Adjective.create(kind: "positive", adjective: "Understanding")
Adjective.create(kind: "positive", adjective: "Versatile")
Adjective.create(kind: "positive", adjective: "Warmhearted")
Adjective.create(kind: "positive", adjective: "Willing")
Adjective.create(kind: "positive", adjective: "Witty")


Adjective.create(kind: "negative", adjective: "Aggressive")
Adjective.create(kind: "negative", adjective: "Aloof")
Adjective.create(kind: "negative", adjective: "Arrogant")
Adjective.create(kind: "negative", adjective: "Belligerent")
Adjective.create(kind: "negative", adjective: "Bigheaded")
Adjective.create(kind: "negative", adjective: "Bitchy")
Adjective.create(kind: "negative", adjective: "Boastful")
Adjective.create(kind: "negative", adjective: "Boneidle")
Adjective.create(kind: "negative", adjective: "Boring")
Adjective.create(kind: "negative", adjective: "Bossy")
Adjective.create(kind: "negative", adjective: "Ballous")
Adjective.create(kind: "negative", adjective: "Cantankerous")
Adjective.create(kind: "negative", adjective: "Careless")
Adjective.create(kind: "negative", adjective: "Changeable")
Adjective.create(kind: "negative", adjective: "Clinging")
Adjective.create(kind: "negative", adjective: "Compulsive")
Adjective.create(kind: "negative", adjective: "Conservative")
Adjective.create(kind: "negative", adjective: "Cowardly")
Adjective.create(kind: "negative", adjective: "Cruel")
Adjective.create(kind: "negative", adjective: "Cunning")
Adjective.create(kind: "negative", adjective: "Cynical")
Adjective.create(kind: "negative", adjective: "Deceitful")
Adjective.create(kind: "negative", adjective: "Detached")
Adjective.create(kind: "negative", adjective: "Dishonest")
Adjective.create(kind: "negative", adjective: "Dogmatic")
Adjective.create(kind: "negative", adjective: "Domineering")
Adjective.create(kind: "negative", adjective: "Finicky")
Adjective.create(kind: "negative", adjective: "Flirtatious")
Adjective.create(kind: "negative", adjective: "Foolish")
Adjective.create(kind: "negative", adjective: "Foolhardy")
Adjective.create(kind: "negative", adjective: "Fussy")
Adjective.create(kind: "negative", adjective: "Greedy")
Adjective.create(kind: "negative", adjective: "Grumpy")
Adjective.create(kind: "negative", adjective: "Gullible")
Adjective.create(kind: "negative", adjective: "Harsh ")
Adjective.create(kind: "negative", adjective: "Impatient")
Adjective.create(kind: "negative", adjective: "Impolite")
Adjective.create(kind: "negative", adjective: "Impulsive")
Adjective.create(kind: "negative", adjective: "Inconsiderate")
Adjective.create(kind: "negative", adjective: "Inconsistent")
Adjective.create(kind: "negative", adjective: "Indecisive")
Adjective.create(kind: "negative", adjective: "Indiscreet")
Adjective.create(kind: "negative", adjective: "Inflexible")
Adjective.create(kind: "negative", adjective: "Interfering")
Adjective.create(kind: "negative", adjective: "Intolerant")
Adjective.create(kind: "negative", adjective: "Irresponsible")
Adjective.create(kind: "negative", adjective: "Jealous")
Adjective.create(kind: "negative", adjective: "Lazy")
Adjective.create(kind: "negative", adjective: "Materialistic")
Adjective.create(kind: "negative", adjective: "Mean")
Adjective.create(kind: "negative", adjective: "Miserly")
Adjective.create(kind: "negative", adjective: "Moody")
Adjective.create(kind: "negative", adjective: "Narrowminded")
Adjective.create(kind: "negative", adjective: "Nasty")
Adjective.create(kind: "negative", adjective: "Naughty")
Adjective.create(kind: "negative", adjective: "Nervous")
Adjective.create(kind: "negative", adjective: "Obsessive")
Adjective.create(kind: "negative", adjective: "Obstinate")
Adjective.create(kind: "negative", adjective: "Overcritical")
Adjective.create(kind: "negative", adjective: "Overemotional")
Adjective.create(kind: "negative", adjective: "Parsimonious")
Adjective.create(kind: "negative", adjective: "Patronizing")
Adjective.create(kind: "negative", adjective: "Perverse")
Adjective.create(kind: "negative", adjective: "Pessimistic")
Adjective.create(kind: "negative", adjective: "Pompous")
Adjective.create(kind: "negative", adjective: "Possessive")
Adjective.create(kind: "negative", adjective: "Pusillanimous")
Adjective.create(kind: "negative", adjective: "Quarrelsome")
Adjective.create(kind: "negative", adjective: "Quicktempered")
Adjective.create(kind: "negative", adjective: "Resentful")
Adjective.create(kind: "negative", adjective: "Rude")
Adjective.create(kind: "negative", adjective: "Ruthless")
Adjective.create(kind: "negative", adjective: "Sarcastic")
Adjective.create(kind: "negative", adjective: "Secretive")
Adjective.create(kind: "negative", adjective: "Selfish")
Adjective.create(kind: "negative", adjective: "Selfcentred")
Adjective.create(kind: "negative", adjective: "Selfindulgent")
Adjective.create(kind: "negative", adjective: "Silly")
Adjective.create(kind: "negative", adjective: "Sneaky")
Adjective.create(kind: "negative", adjective: "Stingy")
Adjective.create(kind: "negative", adjective: "Stubborn")
Adjective.create(kind: "negative", adjective: "Stupid")
Adjective.create(kind: "negative", adjective: "Superficial")
Adjective.create(kind: "negative", adjective: "Tactless")
Adjective.create(kind: "negative", adjective: "Timid")
Adjective.create(kind: "negative", adjective: "Touchy")
Adjective.create(kind: "negative", adjective: "Thoughtless")
Adjective.create(kind: "negative", adjective: "Truculent")
Adjective.create(kind: "negative", adjective: "Unkind")
Adjective.create(kind: "negative", adjective: "Unpredictable")
Adjective.create(kind: "negative", adjective: "Unreliable")
Adjective.create(kind: "negative", adjective: "Untidy")
Adjective.create(kind: "negative", adjective: "Untrustworthy")
Adjective.create(kind: "negative", adjective: "Vague")
Adjective.create(kind: "negative", adjective: "Vain")
Adjective.create(kind: "negative", adjective: "Vengeful")
Adjective.create(kind: "negative", adjective: "Vulgar")
Adjective.create(kind: "negative", adjective: "Weakwilled")